server:
  port: 8090
  servlet:
    contextPath: /v1/users

spring:
  datasource:
    url: jdbc:mysql://localhost/users
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update

appDescription: "Reto plazoletas ms users"
appVersion: "1.0.0"
